packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - concurrently@10.0.6
  - sinterdb-protocol@0.0.1 || 0.1.0
  - sinterdb@0.1.0
